### ISSUE TITLE
NullPointerException thrown when trying to pull or push workspace with docs

### ISSUE THREAD

**Issue by dimitrisfasoulas** [structurizr/onpremises#28]
From build 3002 and onwards, pulling or pushing an update on existing workspace that includes docs, throws a null pointer.

Steps to reproduce:

1. clone https://github.com/dimitrisfasoulas/structurizr-example
2.  start structurizr version 3002 `docker run -it --rm -p 8080:8080 structurizr/onpremises:3002`
3. login to structurizr, create a workspace and copy cli parameters from settings
4.  use structurizr cli to push workspace.dsl `structurizr.sh push -url http://localhost:8080/api -id 1 -key 94435ac8-50d3-466e-b6f5-8395df84c02e -secret 1a0c7e22-07da-4340-ad8b-0eed3baae4ce  -workspace workspace.dsl`
```
structurizr.sh push -url http://localhost:8080/api -id 1 -key 94435ac8-50d3-466e-b6f5-8395df84c02e -secret 1a0c7e22-07da-4340-ad8b-0eed3baae4ce  -workspace workspace.dsl
Pushing workspace 1 to http://localhost:8080/api
 - creating new workspace
 - parsing model and views from /home/gatos/git/structurizr-example/workspace.dsl
 - merge layout from remote: true
 - no views defined; creating default views
 - storing previous version of workspace in null
 - pushing workspace
Getting workspace with ID 1
SoftwareSystem://Service is missing a description.
Putting workspace with ID 1
{"success":true,"message":"OK","revision":2}
 - finished
```
5. try to push again with the same command

```
structurizr.sh push -url http://localhost:8080/api -id 1 -key 94435ac8-50d3-466e-b6f5-8395df84c02e -secret 1a0c7e22-07da-4340-ad8b-0eed3baae4ce  -workspace workspace.dsl
Pushing workspace 1 to http://localhost:8080/api
 - creating new workspace
 - parsing model and views from /home/gatos/git/structurizr-example/workspace.dsl
 - merge layout from remote: true
 - no views defined; creating default views
 - storing previous version of workspace in null
 - pushing workspace
Getting workspace with ID 1
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.structurizr.Workspace["documentation"]->com.structurizr.documentation.Documentation["sections"]->java.util.HashSet[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3690)
        at com.structurizr.io.json.JsonReader.read(JsonReader.java:39)
        at com.structurizr.api.StructurizrClient.getWorkspace(StructurizrClient.java:332)
        at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:373)
        at com.structurizr.cli.PushCommand.run(PushCommand.java:137)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:77)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:112)
Caused by: java.lang.NullPointerException
        at com.structurizr.documentation.Section.hashCode(Section.java:67)
        at java.base/java.util.HashMap.hash(HashMap.java:340)
        at java.base/java.util.HashMap.put(HashMap.java:608)
        at java.base/java.util.HashSet.add(HashSet.java:220)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:363)
        ... 17 more
com.structurizr.io.WorkspaceReaderException: Could not read JSON
com.structurizr.api.StructurizrClientException: com.structurizr.io.WorkspaceReaderException: Could not read JSON
com.structurizr.api.StructurizrClientException: com.structurizr.api.StructurizrClientException: com.structurizr.io.WorkspaceReaderException: Could not read JSON
        at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:420)
        at com.structurizr.cli.PushCommand.run(PushCommand.java:137)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:77)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:112)
Caused by: com.structurizr.api.StructurizrClientException: com.structurizr.io.WorkspaceReaderException: Could not read JSON
        at com.structurizr.api.StructurizrClient.getWorkspace(StructurizrClient.java:353)
        at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:373)
        ... 3 more
Caused by: com.structurizr.io.WorkspaceReaderException: Could not read JSON
        at com.structurizr.io.json.JsonReader.read(JsonReader.java:50)
        at com.structurizr.api.StructurizrClient.getWorkspace(StructurizrClient.java:332)
        ... 4 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.structurizr.Workspace["documentation"]->com.structurizr.documentation.Documentation["sections"]->java.util.HashSet[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3690)
        at com.structurizr.io.json.JsonReader.read(JsonReader.java:39)
        ... 5 more
Caused by: java.lang.NullPointerException
        at com.structurizr.documentation.Section.hashCode(Section.java:67)
        at java.base/java.util.HashMap.hash(HashMap.java:340)
        at java.base/java.util.HashMap.put(HashMap.java:608)
        at java.base/java.util.HashSet.add(HashSet.java:220)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:363)
        ... 17 more
```

Same steps work without problem on version 3001

**Comment by simonbrowndotje** [comment]
If you've updated your on-premises installation, you'll likely need to update your CLI version too.

**Comment by dimitrisfasoulas** [comment]
True. I was using CLI version 1.15.0. Updated to 1.28 and it works. 
Closing this
