### ISSUE TITLE
Embedded diagram in documentation are randomly not rendered due to a SAXParseException

### ISSUE THREAD

**Issue by julienmotch** [structurizr/onpremises#41]
### Description

I've created a workspace which includes diagram and markdown documentation. I've tested locally with Stricturizr Lite and the diagrams as well as teh documentation are all properly rendered.
Now I want to distribute my work by using the shared link option of the On-prem edition. I have imported my local workspace json and when I click on the documentation link, everything seems to be properly rendered however some of the embedded diagram are just rendered as blank.
by looking at the logs of Tomcat I can see the following error:
`
org.xml.sax.SAXParseException; Premature end of file.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
        at com.structurizr.graphviz.SVGReader.parseAndApplyLayout(SVGReader.java:47)
        at com.structurizr.graphviz.GraphvizAutomaticLayout.apply(GraphvizAutomaticLayout.java:129)
        at com.structurizr.onpremises.web.graphviz.GraphvizController.post(GraphvizController.java:75)
        at jdk.internal.reflect.GeneratedMethodAccessor245.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
......
`

And what is surprising is that it is not always the same diagrams that are rendered as blanks. when refrershing the page (F5 under firefox) the diagram pereviously rendered as blank are correctly rendered and at least another one is rendered as blank.

### Steps to reproduce

1. Unzip the file below and open the workspace in Structurizr lite
[ws01.zip](https://github.com/structurizr/onpremises/files/11324519/ws01.zip)

2. You can check that the diagrams and the embedded diagram in documentation are correctly rendered 

3. Import the workspace json fil einto the On-prem edition

4. The diagram are properly rendered

5. The embeded diagram are not all properly rendered (some are blank)

6. Note that the embedded diagram are all properly rendered when importing the workspace in structurizr cloud 

### Screenshot

![image](https://user-images.githubusercontent.com/130443647/234337728-a7b54264-042e-4539-a51d-55b0fa927828.png)

### Configuration

structurizr lite: 3047

structurizr on-prem: 3052

java: open JDK 17 

tomcat: V9

OS: Linux and Windows

### Severity

Minor

### Priority

Medium

### Resolution

I have no budget, please fix this for free

### More information

I will also do my best to have a look at the code to see why it is failling and if I can fix it ;-)

**Comment by simonbrowndotje** [comment]
This should now be fixed in build 3054+.

**Comment by julienmotch** [comment]
Indeed, it is working now when I build from the latest main branch. Thanks!
